In [1]:
import sys
import os

sys.path.append(os.path.abspath("Datasets"))

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2])

In [4]:
b = np.array([3, 4])

In [5]:
zip(a, b)

[(1, 3), (2, 4)]

In [6]:
dot = 0
for e, f in zip(a, b):
    dot += e * f

In [7]:
dot # Dot product of two vector a, b

11

In [8]:
a * b # Multiply element-wise only

array([3, 8])

In [9]:
np.dot(a, b)

11

In [10]:
a.dot(b)

11

In [11]:
a_mag = np.sqrt( (a * a) .sum())

In [12]:
a_mag

2.2360679774997898

In [13]:
a_mag = np.linalg.norm(a)

In [14]:
a_mag

2.2360679774997898

In [15]:
cos_angle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [16]:
cos_angle

0.98386991009990743

In [17]:
angle = np.arccos(cos_angle)

In [18]:
angle # in rad

0.17985349979247847

In [19]:
# Don't use the for loop if you can avoid it

In [20]:
# How to use np.random

In [21]:
L = np.random.random((10, 10))

In [22]:
L # Using uniform distribution to generate samples

array([[ 0.51022924,  0.431493  ,  0.98196452,  0.71947601,  0.11152722,
         0.78020432,  0.14490073,  0.19801237,  0.85722691,  0.65247531],
       [ 0.39206577,  0.379319  ,  0.41611182,  0.96402614,  0.31264215,
         0.90546855,  0.27884409,  0.01324711,  0.08345652,  0.13805548],
       [ 0.51936918,  0.37371727,  0.47803075,  0.00542186,  0.05254589,
         0.86227688,  0.42649158,  0.85120904,  0.12502882,  0.79569936],
       [ 0.57429505,  0.02917949,  0.56339848,  0.29445111,  0.13962454,
         0.81001371,  0.84081041,  0.19814068,  0.49958334,  0.88609027],
       [ 0.02414574,  0.3387291 ,  0.83638059,  0.28303811,  0.54226809,
         0.02604996,  0.91429538,  0.16900983,  0.0833071 ,  0.29463431],
       [ 0.82547882,  0.51754774,  0.10612172,  0.42689241,  0.54376464,
         0.05227715,  0.68519097,  0.4168389 ,  0.39240807,  0.78844777],
       [ 0.96979443,  0.7250665 ,  0.06152947,  0.5989707 ,  0.00745209,
         0.61186281,  0.81502132,  0.44369307

In [23]:
O = np.random.randn(10, 10)

In [24]:
O # Using normal (Gaussian) distribution

array([[-1.78795691, -0.03939308,  0.30044055, -1.19811129, -0.86436705,
        -0.1614294 , -0.48243777,  0.41611772, -1.39461969,  1.09130549],
       [ 0.47179039,  0.55414159,  1.08444427, -1.7274184 ,  0.03803493,
        -1.81159077, -0.81529237, -2.25925511, -0.69106576,  0.31192878],
       [ 0.33631544, -0.80857106,  1.29047912,  0.08590767,  0.35094903,
        -0.24285757, -0.34566358, -0.11061643, -1.45013364,  0.65868155],
       [ 0.05888272, -0.923951  ,  0.20802257,  0.61142348, -1.19219406,
        -2.25963044, -1.57423803, -1.42253787,  0.21435561,  1.0118635 ],
       [-0.37119389, -0.69208953,  0.37042408, -0.18605702, -0.66154485,
         0.71112617, -2.01432161, -0.82928712,  1.00470833,  0.79859979],
       [ 0.49226861,  1.34688999, -0.2236982 , -2.95586266,  0.70703708,
        -0.08045529, -0.65932544,  0.85193884, -1.26030407, -0.91019871],
       [-0.74877786,  0.0805782 , -0.16235208,  0.2590848 , -0.43036718,
        -2.2163256 , -0.5886167 , -0.09699242

In [25]:
A = np.array([[1, 2], [3, 4]])

In [26]:
A_inv = np.linalg.inv(A)

In [27]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
np.linalg.det(A)

-2.0000000000000004

In [29]:
np.diag(A) # Diagonal info of a vector

array([1, 4])

In [30]:
np.diag([1, 2]) # Create a 2-D array of diagonal

array([[1, 0],
       [0, 2]])

In [31]:
a = np.array([1, 2])

In [32]:
b = np.array([3, 4])

In [33]:
np.outer(a, b) # Outer product of A, B

array([[3, 4],
       [6, 8]])

In [34]:
np.diag(A).sum()

5

In [35]:
np.trace(A)

5

In [36]:
# Eigenvalues, eigenvectors
x = np.random.randn(100, 3)

In [37]:
covariance = np.cov(x)

In [38]:
covariance.shape # Wrong, should be 3, 3

(100L, 100L)

In [39]:
covariance = np.cov(x.T)

In [40]:
covariance.shape # True now, have to transpose first

(3L, 3L)

In [41]:
covariance

array([[ 0.93650331,  0.11845328, -0.01346434],
       [ 0.11845328,  0.97167684,  0.07979844],
       [-0.01346434,  0.07979844,  0.92092608]])

In [42]:
np.linalg.eigh(covariance) # eigenvalue, eigenvector

(array([ 0.79955877,  0.93850441,  1.09104306]),
 array([[-0.59879606, -0.57267516,  0.55989859],
        [ 0.63710594,  0.08302929,  0.76629117],
        [-0.4853239 ,  0.81556686,  0.31513714]]))

In [43]:
np.linalg.eig(covariance)

(array([ 1.09104306,  0.79955877,  0.93850441]),
 array([[-0.55989859, -0.59879606, -0.57267516],
        [-0.76629117,  0.63710594,  0.08302929],
        [-0.31513714, -0.4853239 ,  0.81556686]]))

In [44]:
# How to solve a linear system

In [45]:
A = np.array([[1, 2], [3, 4]])

In [46]:
b = np.array([1, 2])

In [47]:
x = np.float16(np.linalg.inv(A).dot(b))

In [48]:
x

array([ 0. ,  0.5], dtype=float16)

In [49]:
# A better way, always use this
x = np.linalg.solve(A, b)

In [50]:
x

array([ 0. ,  0.5])

In [51]:
# A simple example
cost = np.array([[1, 1], [1.5, 4.0]])

In [52]:
result = np.array([2200, 5050])
sol = np.linalg.solve(cost, result)

In [53]:
sol

array([ 1500.,   700.])

# Loading in Data
Structured data - Kaggle and other datasets (Usually CSV)

CSV: comma separated value


In [61]:
X = []
for line in open("Datasets/data_2d.csv"):
    row = line.split(',')
    sample = map(float, row) # Convert string to float
    X.append(sample)

In [62]:
X

[[17.9302012052, 94.5205919533, 320.259529602],
 [97.1446971852, 69.5932819844, 404.634471526],
 [81.7759007845, 5.73764809688, 181.485107741],
 [55.8543424175, 70.3259016768, 321.773638018],
 [49.3665499855, 75.1140401571, 322.465485583],
 [3.19270246506, 29.2562988631, 94.6188108954],
 [49.2007840582, 86.1444385075, 356.348092747],
 [21.882803904, 46.8415051959, 181.653769226],
 [79.5098627219, 87.397355535, 423.557743194],
 [88.1538874975, 65.2056419279, 369.229245443],
 [60.7438543399, 99.9576339008, 427.605803661],
 [67.4155819451, 50.3683096094, 292.471821553],
 [48.3181157719, 99.1289531425, 395.529811407],
 [28.8299719729, 87.1849488537, 319.031348455],
 [43.853742664, 64.4736390798, 287.4281441],
 [25.3136940868, 83.5452942552, 292.768908839],
 [10.807726675, 45.6955685904, 159.663307674],
 [98.365745882, 82.6973935253, 438.798963866],
 [29.1469099692, 66.3651067611, 250.986309034],
 [65.1003018959, 33.3538834975, 231.711507921],
 [24.6441134909, 39.5400527406, 163.398160832],

In [63]:
X = np.array(X)

In [64]:
X.shape

(100L, 3L)

# How to use Pandas
## DataFrames


In [65]:
path

'C:\\Users\\HuuTanVu\\Documents\\studying_ML\\machine_learning_examples-master\\linear_regression_class\\data_2d.csv'

In [66]:
import pandas as pd

In [70]:
X = pd.read_csv("Datasets/data_2d.csv", header=None)

In [71]:
X

0          1           2
0   17.930201  94.520592  320.259530
1   97.144697  69.593282  404.634472
2   81.775901   5.737648  181.485108
3   55.854342  70.325902  321.773638
4   49.366550  75.114040  322.465486
5    3.192702  29.256299   94.618811
6   49.200784  86.144439  356.348093
7   21.882804  46.841505  181.653769
8   79.509863  87.397356  423.557743
9   88.153887  65.205642  369.229245
10  60.743854  99.957634  427.605804
11  67.415582  50.368310  292.471822
12  48.318116  99.128953  395.529811
13  28.829972  87.184949  319.031348
14  43.853743  64.473639  287.428144
15  25.313694  83.545294  292.768909
16  10.807727  45.695569  159.663308
17  98.365746  82.697394  438.798964
18  29.146910  66.365107  250.986309
19  65.100302  33.353883  231.711508
20  24.644113  39.540053  163.398161
21  37.559805   1.345728   83.480155
22  88.164506  95.153663  466.265806
23  13.834621  25.494048  100.886430
24  64.410844  77.259838  365.641048
25  68.925992  97.453601  426.140015
26  39.488442  50.856128  235.532389
27  52.463178  59.776510  283.291640
28  48.484787  66.970354  298.581440
29   8.062088  98.242600  309.234109
..        ...        ...         ...
70  30.187692   7.146539   89.539008
71  11.788418  51.697761  181.550683
72  18.292424  61.977976  224.773383
73  96.712668   9.029102  219.567094
74  31.012739  78.283382  298.490216
75  11.397261  61.728693  199.944045
76  17.392556   4.241141   43.915692
77  72.182694  34.539072  256.068378
78  73.980021   3.716493  159.372581
79  94.493058  88.417197  447.132704
80  84.562821  20.241162  233.078830
81  51.742474  11.009748  131.070180
82  53.748590  60.025102  298.814333
83  85.050835  95.736997  451.803523
84  46.777250  90.202206  368.366436
85  49.758434  52.834494  254.706774
86  24.119257  42.102811  168.308433
87  27.201576  29.978749  146.342260
88   7.009596  55.876058  176.810149
89  97.646950   8.147625  219.160280
90   1.382983  84.944087  252.905653
91  22.323530  27.515075  127.570479
92  45.045406  93.520402  375.822340
93  40.163991   0.161699   80.389019
94  53.182740   8.170316  142.718183
95  46.456779  82.000171  336.876154
96  77.130301  95.188759  438.460586
97  68.600608  72.571181  355.900287
98  41.693887  69.241126  284.834637
99   4.142669  52.254726  168.034401

[100 rows x 3 columns]

In [72]:
X.shape
type(X)

pandas.core.frame.DataFrame

In [73]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB


In [74]:
X.head(10)

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486
5   3.192702  29.256299   94.618811
6  49.200784  86.144439  356.348093
7  21.882804  46.841505  181.653769
8  79.509863  87.397356  423.557743
9  88.153887  65.205642  369.229245

In [75]:
X[0] # Pandas returns column with name 0

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...    
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, dtype: float64

In [76]:
type(X[0])

pandas.core.series.Series

In [77]:
X.iloc[0] # To get row 0

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [78]:
X.ix[0] # Same

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [79]:
X[[0, 2]]

0           2
0   17.930201  320.259530
1   97.144697  404.634472
2   81.775901  181.485108
3   55.854342  321.773638
4   49.366550  322.465486
5    3.192702   94.618811
6   49.200784  356.348093
7   21.882804  181.653769
8   79.509863  423.557743
9   88.153887  369.229245
10  60.743854  427.605804
11  67.415582  292.471822
12  48.318116  395.529811
13  28.829972  319.031348
14  43.853743  287.428144
15  25.313694  292.768909
16  10.807727  159.663308
17  98.365746  438.798964
18  29.146910  250.986309
19  65.100302  231.711508
20  24.644113  163.398161
21  37.559805   83.480155
22  88.164506  466.265806
23  13.834621  100.886430
24  64.410844  365.641048
25  68.925992  426.140015
26  39.488442  235.532389
27  52.463178  283.291640
28  48.484787  298.581440
29   8.062088  309.234109
..        ...         ...
70  30.187692   89.539008
71  11.788418  181.550683
72  18.292424  224.773383
73  96.712668  219.567094
74  31.012739  298.490216
75  11.397261  199.944045
76  17.392556   43.915692
77  72.182694  256.068378
78  73.980021  159.372581
79  94.493058  447.132704
80  84.562821  233.078830
81  51.742474  131.070180
82  53.748590  298.814333
83  85.050835  451.803523
84  46.777250  368.366436
85  49.758434  254.706774
86  24.119257  168.308433
87  27.201576  146.342260
88   7.009596  176.810149
89  97.646950  219.160280
90   1.382983  252.905653
91  22.323530  127.570479
92  45.045406  375.822340
93  40.163991   80.389019
94  53.182740  142.718183
95  46.456779  336.876154
96  77.130301  438.460586
97  68.600608  355.900287
98  41.693887  284.834637
99   4.142669  168.034401

[100 rows x 2 columns]

In [80]:
X[X[0] < 5]

0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
54  4.593463  46.335932  145.818745
90  1.382983  84.944087  252.905653
99  4.142669  52.254726  168.034401

In [81]:
type(X[0] < 5)

pandas.core.series.Series

In [82]:
M = X.as_matrix() # Still return an ndarray
type(M)

numpy.ndarray

In [83]:
X.head(5)

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486

## Dealing with csv file having ugly headers, redundant footers

In [84]:
csv_file = "Datasets/international-airline-passengers.csv"

In [85]:
import pandas as pd

In [86]:
df = pd.read_csv(csv_file, engine="python", skipfooter=3)

### Explain
skipfooter = 3 : Remove the last 3 rows
engine="python": skipfooter cannot work with default engine

In [87]:
df.columns

Index([u'Month', u'International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60'], dtype='object')

In [88]:
df.columns = ["month", "passengers"]

In [89]:
df.columns

Index([u'month', u'passengers'], dtype='object')

In [90]:
df['passengers']

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
      ... 
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
143    432
Name: passengers, dtype: int64

In [91]:
df.passengers

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
      ... 
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
143    432
Name: passengers, dtype: int64

In [92]:
df['ones'] = 1

In [94]:
df.head()

month  passengers  ones
0  1949-01         112     1
1  1949-02         118     1
2  1949-03         132     1
3  1949-04         129     1
4  1949-05         121     1

### How to use Apply function


In [95]:
from datetime import datetime

In [96]:
datetime.strptime("1949-05", "%Y-%m")

datetime.datetime(1949, 5, 1, 0, 0)

In [97]:
df['dt'] = df.apply(lambda row: datetime.strptime(row['month'],
                                                 "%Y-%m"), axis=1)

In [98]:
df.head()

month  passengers  ones         dt
0  1949-01         112     1 1949-01-01
1  1949-02         118     1 1949-02-01
2  1949-03         132     1 1949-03-01
3  1949-04         129     1 1949-04-01
4  1949-05         121     1 1949-05-01

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 4 columns):
month         144 non-null object
passengers    144 non-null int64
ones          144 non-null int64
dt            144 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 4.6+ KB


In [100]:
t1 = pd.read_csv('Datasets/table1.csv')
t2 = pd.read_csv('Datasets/table2.csv')

In [101]:
m = pd.merge(t1, t2, on='user_id')

In [102]:
m

user_id            email  age  ad_id  click
0         1  alice@gmail.com   20      1      1
1         1  alice@gmail.com   20      2      0
2         1  alice@gmail.com   20      5      0
3         2    bob@gmail.com   25      3      0
4         2    bob@gmail.com   25      4      1
5         2    bob@gmail.com   25      1      0
6         3  carol@gmail.com   30      2      0
7         3  carol@gmail.com   30      1      0
8         3  carol@gmail.com   30      3      0
9         3  carol@gmail.com   30      4      0
10        3  carol@gmail.com   30      5      1

In [103]:
t1.merge(t2, on="user_id")

user_id            email  age  ad_id  click
0         1  alice@gmail.com   20      1      1
1         1  alice@gmail.com   20      2      0
2         1  alice@gmail.com   20      5      0
3         2    bob@gmail.com   25      3      0
4         2    bob@gmail.com   25      4      1
5         2    bob@gmail.com   25      1      0
6         3  carol@gmail.com   30      2      0
7         3  carol@gmail.com   30      1      0
8         3  carol@gmail.com   30      3      0
9         3  carol@gmail.com   30      4      0
10        3  carol@gmail.com   30      5      1